name: Test Coverage Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-groups
      - name: Generate the coverage report
        run: |
          uv run coverage run --source=otelize/tests -m unittest
          uv run coverage report --fail-under=100
          uv run coverage xml -o coverage.xml
